language: java
jdk: oraclejdk7
before_install:
  # Install some needed libs and don't print anything meanwhile
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch >/dev/null; fi
  # Download the latest android sdk and unzip it
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xzf android-sdk_r22.3-linux.tgz
  # Setup ANDROID_HOME and PATH environment variables
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Install Android SDK an other tools
  #- echo yes | android update sdk --force --no-ui
  - echo yes | android update sdk --filter platform-tools --no-ui --force
  - echo yes | android update sdk --filter extra-android-support --no-ui --force
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force
  - echo yes | android update sdk --filter android-18 --force --no-ui
  - echo yes | android update sdk --filter android-14 --force --no-ui
  - echo yes | android update sdk --filter build-tools-19.0.0 --force --no-ui
  - echo yes | android update sdk --filter sysimg-18 --force --no-ui
  - ls $ANDROID_HOME/build-tools/

after_success:
  - curl "http://reinoslokos.no-ip.org/index.php?title=Travis.ci&description=Build%20$TRAVIS_BUILD_NUMBER%20($TRAVIS_BUILD_ID)%20completado%20correctamente"
after_failure:
  - curl "http://reinoslokos.no-ip.org/index.php?title=Travis.ci&description=Build%20$TRAVIS_BUILD_NUMBER%20($TRAVIS_BUILD_ID)%20ha%20fallado"

#script: mvn -Pcobertura cobertura:cobertura coveralls:cobertura
